name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load VITE_ENV_VARS
        run: |
          echo '${{ secrets.VITE_ENV_VARS }}' > env.json
          cat env.json | jq -r 'to_entries | map("export \(.key)=\(.value|tostring)") | .[]' >> $GITHUB_ENV

      # - name: Debug environment variables
      #   run: env | grep VITE_

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEXTUP_APP_91E19 }}
          channelId: live
          projectId: nextup-app-91e19